import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Banner from "@/components/Banner";


export const metadata: Metadata = {
  title: "Beatbike",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className='bg-black h-screen'>
        <Header />
        <Banner />
        {children}
        <Footer />
      </body>
    </html>
  );
}
