import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Announcement from "@/components/Announcement";


export const metadata: Metadata = {
  title: "Beatbike",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className='bg-black'>
        <Announcement />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
